#!/usr/bin/env python3
"""Observe Codex's shell hook contract; not a Guardrail enforcement test.

Only fixed echo/pwd commands run. No credentials or model service are used.
User settings are untouched; all generated settings and logs are disposable.
"""

import argparse
import base64
import http.server
import json
import os
from pathlib import Path
import shlex
import subprocess
import sys
import tempfile
import threading

from codex_probe_support import resolve_command, run_probe_command, probe_timeout, toml_string


def contract_cases(workspace, alternate, shells):
    cases = []
    for shell in [None, *shells]:
        for directory in [workspace, alternate]:
            args = {"cmd": "echo GR_EXEC_CONTRACT; pwd", "workdir": str(directory), "login": False}
            if shell:
                args["shell"] = shell
            cases.append({"id": f"call_{len(cases)}", "args": args, "marker": "GR_EXEC_CONTRACT"})
    return cases


def summarize_case(case, events, output, *, code_mode=False):
    # Code mode gets an isolated, sequential provider-request event window:
    # nested hook IDs are generated by Codex, not the outer Responses call ID.
    pre = [event for event in events if event.get("hook_event_name") == "PreToolUse"
           and (code_mode or event.get("tool_use_id") == case["id"])]
    execution_output = output
    encoded_output = output
    if output.startswith("Script completed\n"):
        encoded_output = output.partition("\nOutput:\n")[2].strip()
    try:
        decoded = json.loads(encoded_output)
        if isinstance(decoded, dict) and isinstance(decoded.get("output"), str):
            execution_output = decoded["output"]
    except (ValueError, TypeError):
        pass
    return {
        "requested": case,
        "hook_count": len(pre),
        "dispatch_complete": len(pre) == 1 and pre[0].get("tool_name") == "Bash" and pre[0].get("tool_input", {}).get("command") == case["args"]["cmd"],
        "hook_input": pre[0] if len(pre) == 1 else None,
        "executed": case["marker"] in [line.strip() for line in execution_output.splitlines()],
        # Neither a model-supplied shell nor the hook process's own shell is
        # evidence of the executor's interpreter. No verified host-owned
        # execution-context schema exists in this adapter yet. Retain raw
        # input so a changed Codex contract can be reviewed, never guessed.
        "execution_context_available": False,
        "tool_output": output,
    }


def record_hook(path):
    payload = json.load(sys.stdin)
    with Path(path).open("a", encoding="utf-8") as stream:
        stream.write(json.dumps(payload) + "\n")


def observer_command(log):
    args = [sys.executable, "-B", str(Path(__file__).resolve()), "--record-hook", str(log)]
    if os.name != "nt":
        return shlex.join(args)
    # Inherit stdin directly: Windows PowerShell pipelines can prepend a BOM.
    script = "& " + " ".join("'" + arg.replace("'", "''") + "'" for arg in args) + "; exit $LASTEXITCODE"
    encoded = base64.b64encode(script.encode("utf-16le")).decode("ascii")
    return "powershell.exe -NoLogo -NoProfile -NonInteractive -EncodedCommand " + encoded


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--record-hook", help=argparse.SUPPRESS)
    parser.add_argument("--code-mode", action="store_true")
    parser.add_argument("--require-context", action="store_true", help="exit 2 until a reviewed host execution-context contract is available")
    options = parser.parse_args()
    if options.record_hook:
        record_hook(options.record_hook)
        return 0
    windows = os.name == "nt"
    codex = resolve_command("codex", windows=windows)
    if not codex:
        print("SKIP: native Codex required", file=sys.stderr)
        return 77
    root = Path(tempfile.mkdtemp(prefix="codex-execution-contract-"))
    workspace = root / "workspace"
    alternate = workspace / "space dir unicode-é"
    alternate.mkdir(parents=True)
    config = root / "codex"
    config.mkdir()
    log = root / "hooks.jsonl"
    hook = {"type": "command", "command": observer_command(log), "timeout": 30}
    (config / "hooks.json").write_text(json.dumps({"hooks": {
        "PreToolUse": [{"matcher": "*", "hooks": [hook]}],
        "PostToolUse": [{"matcher": "*", "hooks": [hook]}],
    }}), encoding="utf-8")
    shell_names = ["pwsh", "powershell"] if windows else ["bash", "sh"]
    shells = [path for name in shell_names if (path := resolve_command(name, windows=windows))]
    cases = contract_cases(workspace, alternate, shells)
    requests = []
    event_windows = {}
    event_cursor = 0

    def read_events():
        return [json.loads(line) for line in log.read_text(encoding="utf-8").splitlines()] if log.exists() else []

    class Handler(http.server.BaseHTTPRequestHandler):
        def log_message(self, *_):
            pass

        def do_POST(self):
            nonlocal event_cursor
            request = json.loads(self.rfile.read(int(self.headers["Content-Length"])))
            requests.append(request)
            index = len(requests) - 1
            if 0 < index <= len(cases):
                observed = read_events()
                event_windows[cases[index - 1]["id"]] = observed[event_cursor:]
                event_cursor = len(observed)
            if index < len(cases):
                case = cases[index]
                item = {"id": f"item_{index}", "call_id": case["id"], "status": "completed"}
                if options.code_mode:
                    item.update(type="custom_tool_call", name="exec", input="text(await tools.exec_command(" + json.dumps(case["args"]) + "));")
                else:
                    item.update(type="function_call", name="exec_command", arguments=json.dumps(case["args"]))
            else:
                item = {"type": "message", "id": "msg_final", "role": "assistant", "status": "completed", "content": [{"type": "output_text", "text": "Execution contract probe complete.", "annotations": []}]}
            response = {"id": f"resp_{index}", "object": "response", "status": "in_progress", "output": []}
            events = [
                {"type": "response.created", "response": response},
                {"type": "response.output_item.added", "output_index": 0, "item": item},
                {"type": "response.output_item.done", "output_index": 0, "item": item},
                {"type": "response.completed", "response": {**response, "status": "completed", "output": [item], "usage": {"input_tokens": 1, "output_tokens": 1, "total_tokens": 2}}},
            ]
            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.end_headers()
            for event in events:
                self.wfile.write(("event: " + event["type"] + "\ndata: " + json.dumps(event) + "\n\n").encode())
            self.wfile.flush()

    server = http.server.ThreadingHTTPServer(("127.0.0.1", 0), Handler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    catalog = json.loads((Path(__file__).resolve().parents[1] / "fixtures/codex/model-catalog.json").read_text(encoding="utf-8"))
    if options.code_mode:
        catalog["models"][0]["tool_mode"] = "code_mode_only"
    catalog_path = config / "model-catalog.json"
    catalog_path.write_text(json.dumps(catalog), encoding="utf-8")
    (config / "config.toml").write_text(f'''model = "codex-fixture"
model_provider = "fixture"
model_catalog_json = {toml_string(catalog_path)}
web_search = "disabled"
[model_providers.fixture]
name = "Local execution-contract fixture"
base_url = "http://127.0.0.1:{server.server_port}/v1"
wire_api = "responses"
requires_openai_auth = false
[features]
shell_snapshot = false
''', encoding="utf-8")
    env = dict(os.environ, CODEX_HOME=str(config))
    command = [codex, "exec", "--ephemeral", "--skip-git-repo-check", "--dangerously-bypass-hook-trust", "--sandbox", "read-only", "-C", str(workspace), "Run the fixed read-only execution contract probes."]
    try:
        result = run_probe_command(command, env=env, timeout=probe_timeout(windows=windows))
    finally:
        server.shutdown()
        server.server_close()
    for filename, value in [("stdout.txt", result.stdout), ("stderr.txt", result.stderr), ("requests.json", json.dumps(requests, indent=2))]:
        (root / filename).write_text(value, encoding="utf-8")
    events = read_events()
    outputs = {}
    for request in requests:
        for item in request.get("input", []):
            if item.get("type", "").endswith("_output"):
                output = item.get("output", "")
                if isinstance(output, list):
                    output = "\n".join(part.get("text", "") for part in output)
                outputs[item.get("call_id")] = str(output)
    observations = [summarize_case(case, event_windows.get(case["id"], []) if options.code_mode else events,
                                   outputs.get(case["id"], ""), code_mode=options.code_mode) for case in cases]
    report = {
        "codex": subprocess.check_output([codex, "--version"], env=env, text=True).strip(),
        "platform": sys.platform, "code_mode": options.code_mode,
        "codex_exit": result.returncode, "requests": len(requests),
        "observations": observations, "artifacts": str(root),
        "enforcement_tested": False,
        "context_status": "unverified: no reviewed host-owned shell/argv/effective-cwd contract",
    }
    incomplete = result.returncode or len(requests) != len(cases) + 1 or not all(item["dispatch_complete"] and item["executed"] for item in observations)
    report["probe_exit"] = 1 if incomplete else (2 if options.require_context else 0)
    report["advertised_tools"] = requests[0].get("tools", []) if requests else []
    (root / "report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps({key: value for key, value in report.items() if key != "advertised_tools"}, indent=2))
    return report["probe_exit"]


if __name__ == "__main__":
    sys.exit(main())
