package genconfig

import (
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"unicode/utf16"
)

func TestCodexMergeRemoveAndDrift(t *testing.T) {
	path := filepath.Join(t.TempDir(), "hooks.json")
	if err := os.WriteFile(path, []byte(`{"description":"keep","hooks":{"PreToolUse":[{"hooks":[{"type":"command","command":"user-hook"}]}]}}`), 0600); err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 2; i++ {
		if err := MergePlaneInto(path, "codex", CodexConfig("/opt/my tool/guardrail")); err != nil {
			t.Fatal(err)
		}
	}
	raw, _ := os.ReadFile(path)
	if strings.Count(string(raw), `"id": "guardrail-codex-PreToolUse"`) != 1 || !strings.Contains(string(raw), "user-hook") {
		t.Fatal(string(raw))
	}
	var doc map[string]any
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	if !CodexHooksRegistered(doc) {
		t.Fatal("not registered")
	}
	hooks := doc["hooks"].(map[string]any)
	var pre map[string]any
	for _, raw := range hooks["PreToolUse"].([]any) {
		group := raw.(map[string]any)
		if group["id"] == "guardrail-codex-PreToolUse" {
			pre = group
			break
		}
	}
	if pre == nil {
		t.Fatal("owned PreToolUse group missing")
	}
	handler := pre["hooks"].([]any)[0].(map[string]any)
	windowsCommand := handler["commandWindows"]
	delete(handler, "commandWindows")
	if CodexHooksRegistered(doc) {
		t.Fatal("missing Windows command accepted")
	}
	handler["commandWindows"] = windowsCommand
	handler["commandWindows"] = windowsCommand.(string) + " & if errorlevel 2 (exit /b 2)"
	if CodexHooksRegistered(doc) {
		t.Fatal("stale CMD-specific Windows suffix accepted")
	}
	handler["commandWindows"] = windowsCommand
	delete(hooks, "PreToolUse")
	if CodexHooksRegistered(doc) {
		t.Fatal("missing pre accepted")
	}
	if err := RemovePlaneFrom(path, "codex"); err != nil {
		t.Fatal(err)
	}
	raw, _ = os.ReadFile(path)
	if strings.Contains(string(raw), "guardrail-codex") || !strings.Contains(string(raw), "user-hook") || !strings.Contains(string(raw), "keep") {
		t.Fatal(string(raw))
	}
}

func TestWindowsCodexHandlersCarryInspectableIdentityAndHash(t *testing.T) {
	hooks := CodexConfig("/opt/guardrail")["hooks"].(map[string]any)
	seenHashes := map[string]bool{}
	for _, event := range []string{"PreToolUse", "PostToolUse", "SessionStart"} {
		group := hooks[event].([]any)[0].(map[string]any)
		handler := group["hooks"].([]any)[0].(map[string]any)
		wantID := "guardrail-codex-" + event
		for _, command := range []string{handler["command"].(string), decodePowerShellForTest(t, handler["commandWindows"].(string))} {
			if !strings.Contains(command, "--handler-id") || !strings.Contains(command, wantID) {
				t.Fatalf("%s command lacks handler identity: %s", event, command)
			}
			i := strings.Index(command, "sha256:")
			if i < 0 || len(command) < i+len("sha256:")+64 {
				t.Fatalf("%s command lacks sha256 handler hash: %s", event, command)
			}
			hash := command[i : i+len("sha256:")+64]
			if seenHashes[hash] {
				t.Fatalf("handler hash %s reused across event-specific commands", hash)
			}
			seenHashes[hash] = true
		}
	}
}

func decodePowerShellForTest(t *testing.T, command string) string {
	t.Helper()
	const marker = "-EncodedCommand "
	start := strings.Index(command, marker)
	if start < 0 {
		t.Fatalf("missing %s: %s", marker, command)
	}
	encoded := strings.Fields(command[start+len(marker):])[0]
	raw, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil || len(raw)%2 != 0 {
		t.Fatalf("decode PowerShell command: %v", err)
	}
	units := make([]uint16, len(raw)/2)
	for i := range units {
		units[i] = binary.LittleEndian.Uint16(raw[i*2:])
	}
	return string(utf16.Decode(units))
}

func TestCodexRulesOwnership(t *testing.T) {
	hooks := filepath.Join(t.TempDir(), "hooks.json")
	if err := WriteCodexRules(hooks); err != nil {
		t.Fatal(err)
	}
	if err := WriteCodexRules(hooks); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(filepath.Dir(hooks), "rules", "guardrail.rules")
	if err := os.WriteFile(path, []byte("# user-owned\n"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := WriteCodexRules(hooks); err == nil {
		t.Fatal("overwrote user file")
	}
}

func TestCodexWrapperOwnershipAndExecution(t *testing.T) {
	dir := t.TempDir()
	hooks := filepath.Join(dir, "hooks.json")
	binary := "/usr/local/bin/guardrail"
	if err := WriteCodexWrapper(hooks, binary); err != nil {
		t.Fatal(err)
	}
	wrapperPath := filepath.Join(dir, "guardrail-hook.cmd")
	content, err := os.ReadFile(wrapperPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(content), "@rem Generated by Guardrail.") {
		t.Fatalf("missing ownership header: %s", string(content))
	}
	if !strings.Contains(string(content), `"/usr/local/bin/guardrail" hook codex %*`) {
		t.Fatalf("missing binary invocation: %s", string(content))
	}
	if !strings.Contains(string(content), `if "%guardrail_exit%"=="2" exit /b 2`) {
		t.Fatalf("wrapper does not preserve policy-denial exit 2: %s", string(content))
	}
	if !strings.Contains(string(content), "guardrail: handler failure: evaluator exited with code %guardrail_exit%") {
		t.Fatalf("wrapper does not classify evaluator failure: %s", string(content))
	}
	if strings.Contains(string(content), "transport failure") {
		t.Fatalf("wrapper misclassifies an invoked handler as transport failure: %s", string(content))
	}
	// Verify CodexConfigFor uses the wrapper
	frag := CodexConfigFor(hooks, binary)
	hooksMap := frag["hooks"].(map[string]any)
	group := hooksMap["PreToolUse"].([]any)[0].(map[string]any)
	handler := group["hooks"].([]any)[0].(map[string]any)
	cmdWin := handler["commandWindows"].(string)
	if !strings.Contains(cmdWin, "-EncodedCommand") {
		t.Fatalf("commandWindows does not contain -EncodedCommand: %s", cmdWin)
	}
	windowsScript := decodePowerShellForTest(t, cmdWin)
	if !strings.Contains(windowsScript, "guardrail-hook.cmd") {
		t.Fatalf("encoded commandWindows does not reference wrapper: %s", windowsScript)
	}
	if !strings.Contains(windowsScript, "--handler-id 'guardrail-codex-PreToolUse'") || !strings.Contains(windowsScript, "--handler-hash 'sha256:") {
		t.Fatalf("encoded commandWindows does not carry inspectable diagnostic identity: %s", windowsScript)
	}
	// Verify CodexHooksRegistered accepts it
	doc := map[string]any{"hooks": hooksMap}
	if !CodexHooksRegistered(doc) {
		t.Fatal("CodexHooksRegistered rejected wrapper hook")
	}
}

func TestWindowsCodexInstalledCommandRunsUnderPowerShell(t *testing.T) {
	if runtime.GOOS != "windows" {
		t.Skip("PowerShell command handlers execute only on Windows")
	}
	pwsh, err := exec.LookPath("pwsh.exe")
	if err != nil {
		t.Skip("pwsh.exe is required to exercise Codex's configured Windows shell")
	}
	dir := filepath.Join(t.TempDir(), "codex hooks")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	hooksPath := filepath.Join(dir, "hooks.json")
	binary := filepath.Join(dir, "guardrail.cmd")
	if err := os.WriteFile(binary, []byte("@findstr /c:\"session_id\" >nul || exit /b 9\r\n@exit /b %GUARDRAIL_TEST_EXIT%\r\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := WriteCodexWrapper(hooksPath, binary); err != nil {
		t.Fatal(err)
	}

	frag := CodexConfigFor(hooksPath, binary)
	hooks := frag["hooks"].(map[string]any)
	group := hooks["PreToolUse"].([]any)[0].(map[string]any)
	command := group["hooks"].([]any)[0].(map[string]any)["commandWindows"].(string)
	for _, test := range []struct {
		name      string
		exit      string
		wantBlock bool
	}{
		{name: "evaluator allows", exit: "0"},
		{name: "policy denies", exit: "2", wantBlock: true},
		{name: "evaluator crashes", exit: "7", wantBlock: true},
	} {
		t.Run(test.name, func(t *testing.T) {
			cmd := exec.Command(pwsh, "-NoProfile", "-NonInteractive", "-Command", command)
			cmd.Env = append(os.Environ(), "GUARDRAIL_TEST_EXIT="+test.exit)
			cmd.Stdin = strings.NewReader(`{"session_id":"fixture","hook_event_name":"PreToolUse"}`)
			var stdout strings.Builder
			var stderr strings.Builder
			cmd.Stdout = &stdout
			cmd.Stderr = &stderr
			_ = cmd.Run()
			if got := cmd.ProcessState.ExitCode(); got != 0 {
				t.Fatalf("exit = %d, want 0; stdout: %s; stderr: %s; command: %s", got, stdout.String(), stderr.String(), command)
			}
			if got := strings.Contains(stdout.String(), `"permissionDecision":"deny"`); got != test.wantBlock {
				t.Fatalf("blocking JSON = %t, want %t; stdout: %s; stderr: %s", got, test.wantBlock, stdout.String(), stderr.String())
			}
		})
	}
}

func TestWindowsCodexInstalledBlocksUseEventSpecificJSON(t *testing.T) {
	if runtime.GOOS != "windows" {
		t.Skip("PowerShell command handlers execute only on Windows")
	}
	pwsh, err := exec.LookPath("pwsh.exe")
	if err != nil {
		t.Skip("pwsh.exe is required to exercise Codex's configured Windows shell")
	}
	dir := t.TempDir()
	hooksPath := filepath.Join(dir, "hooks.json")
	binary := filepath.Join(dir, "guardrail.cmd")
	if err := os.WriteFile(binary, []byte("@exit /b 2\r\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := WriteCodexWrapper(hooksPath, binary); err != nil {
		t.Fatal(err)
	}
	hooks := CodexConfigFor(hooksPath, binary)["hooks"].(map[string]any)
	for _, test := range []struct {
		event string
		want  string
	}{
		{event: "PreToolUse", want: `"permissionDecision":"deny"`},
		{event: "PostToolUse", want: `"decision":"block"`},
		{event: "SessionStart", want: `"continue":false`},
	} {
		t.Run(test.event, func(t *testing.T) {
			group := hooks[test.event].([]any)[0].(map[string]any)
			command := group["hooks"].([]any)[0].(map[string]any)["commandWindows"].(string)
			cmd := exec.Command(pwsh, "-NoProfile", "-NonInteractive", "-Command", command)
			cmd.Stdin = strings.NewReader(`{"session_id":"fixture","hook_event_name":"` + test.event + `"}`)
			var stdout, stderr strings.Builder
			cmd.Stdout, cmd.Stderr = &stdout, &stderr
			_ = cmd.Run()
			if got := cmd.ProcessState.ExitCode(); got != 0 || !strings.Contains(stdout.String(), test.want) {
				t.Fatalf("exit=%d stdout=%q stderr=%q, want structured %s block", got, stdout.String(), stderr.String(), test.event)
			}
		})
	}
}

func TestWindowsCodexInstalledCommandHasNoEmbeddedQuotes(t *testing.T) {
	hooksPath := filepath.Join("safe", "codex", "hooks.json")
	frag := CodexConfigFor(hooksPath, filepath.Join("safe", "bin", "guardrail.exe"))
	hooks := frag["hooks"].(map[string]any)

	for _, event := range []string{"PreToolUse", "PostToolUse", "SessionStart"} {
		group := hooks[event].([]any)[0].(map[string]any)
		handler := group["hooks"].([]any)[0].(map[string]any)
		command := handler["commandWindows"].(string)
		if strings.Contains(command, `"`) {
			t.Fatalf("%s commandWindows contains an embedded quote that Codex misparses on Windows: %s", event, command)
		}
	}
}

func TestWindowsCodexInstalledCommandEncodesUnsafeWrapperPath(t *testing.T) {
	hooksPath := filepath.Join("path with spaces", "codex", "hooks.json")
	frag := CodexConfigFor(hooksPath, filepath.Join("path with spaces", "bin", "guardrail.exe"))
	hooks := frag["hooks"].(map[string]any)
	group := hooks["PreToolUse"].([]any)[0].(map[string]any)
	handler := group["hooks"].([]any)[0].(map[string]any)
	command := handler["commandWindows"].(string)

	if strings.Contains(command, `"`) {
		t.Fatalf("commandWindows exposes an embedded quote to Codex: %s", command)
	}
	script := decodePowerShellForTest(t, command)
	wrapperPath := filepath.Join(filepath.Dir(hooksPath), "guardrail-hook.cmd")
	if !strings.Contains(script, "$wrapperPath = '"+wrapperPath+"'") || !strings.Contains(script, "& $wrapperPath --handler-id 'guardrail-codex-PreToolUse'") {
		t.Fatalf("encoded command does not invoke the owned wrapper: %s", script)
	}
	if !CodexHooksRegistered(map[string]any{"hooks": hooks}) {
		t.Fatal("CodexHooksRegistered rejected encoded wrapper hook")
	}
}

func TestCodexMissingBinaryBlocksAndQuotedPathCannotExecute(t *testing.T) {
	sh, err := exec.LookPath("sh")
	if err != nil {
		t.Skip("sh is required to exercise Unix command invocation")
	}
	marker := filepath.Join(t.TempDir(), "must-not-exist")
	binary := "/missing/guardrail'; touch " + marker + "; '"
	hooks := CodexConfig(binary)["hooks"].(map[string]any)
	group := hooks["PreToolUse"].([]any)[0].(map[string]any)
	command := group["hooks"].([]any)[0].(map[string]any)["command"].(string)
	cmd := exec.Command(sh, "-c", command)
	var stderr strings.Builder
	cmd.Stderr = &stderr
	if err := cmd.Run(); err == nil || cmd.ProcessState.ExitCode() != 2 {
		t.Fatalf("missing binary did not block: %v", err)
	}
	if !strings.Contains(stderr.String(), "guardrail: transport failure:") || strings.Contains(stderr.String(), "policy denial") {
		t.Fatalf("missing binary diagnostic = %q, want transport failure only", stderr.String())
	}
	if _, err := os.Stat(marker); !os.IsNotExist(err) {
		t.Fatal("binary path was interpreted as shell code")
	}
}

func TestCodexWindowsCommandRunsAndReturnsStructuredBlocks(t *testing.T) {
	if runtime.GOOS != "windows" {
		t.Skip("Windows command handlers execute through cmd.exe")
	}
	dir := filepath.Join(t.TempDir(), "guardrail tools & helpers 'quoted'")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	binary := filepath.Join(dir, "guardrail.cmd")
	if err := os.WriteFile(binary, []byte("@findstr /c:\"session_id\" >nul || exit /b 9\r\n@exit /b %GUARDRAIL_TEST_EXIT%\r\n"), 0o755); err != nil {
		t.Fatal(err)
	}

	frag := CodexConfig(binary)
	hooks := frag["hooks"].(map[string]any)
	group := hooks["PreToolUse"].([]any)[0].(map[string]any)
	handler := group["hooks"].([]any)[0].(map[string]any)
	command, ok := handler["commandWindows"].(string)
	if !ok || command == "" {
		t.Fatalf("Windows command override = %#v, want nonempty string", handler["commandWindows"])
	}

	for _, test := range []struct {
		name      string
		exit      string
		wantBlock string
	}{
		{name: "evaluator allows", exit: "0"},
		{name: "policy denies without transport noise", exit: "2", wantBlock: `"permissionDecision":"deny"`},
		{name: "evaluator crashes", exit: "7", wantBlock: "guardrail: handler failure: evaluator exited with code 7"},
	} {
		t.Run(test.name, func(t *testing.T) {
			if _, err := os.Stat(binary); err != nil {
				t.Fatalf("fixture binary before invocation: %v", err)
			}
			cmd := exec.Command(os.Getenv("ComSpec"), "/d", "/s", "/c", command)
			cmd.Env = append(os.Environ(), "GUARDRAIL_TEST_EXIT="+test.exit)
			cmd.Stdin = strings.NewReader(`{"session_id":"fixture","hook_event_name":"PreToolUse"}`)
			var stdout strings.Builder
			var stderr strings.Builder
			cmd.Stdout = &stdout
			cmd.Stderr = &stderr
			_ = cmd.Run()
			if got := cmd.ProcessState.ExitCode(); got != 0 {
				t.Fatalf("exit = %d, want 0; stdout=%q stderr=%q; command: %s", got, stdout.String(), stderr.String(), command)
			}
			if got := stdout.String(); (test.wantBlock == "" && got != "") || (test.wantBlock != "" && !strings.Contains(got, test.wantBlock)) || strings.Contains(got, "evaluator unavailable or blocked") {
				t.Fatalf("stdout = %q, want block %q and no conflated fallback; stderr=%q", got, test.wantBlock, stderr.String())
			}
			if _, err := os.Stat(binary); err != nil {
				t.Fatalf("fixture binary after invocation: %v", err)
			}
		})
	}
}

func TestCodexWindowsMissingBinaryReturnsStructuredTransportBlock(t *testing.T) {
	if runtime.GOOS != "windows" {
		t.Skip("Windows command handlers execute through cmd.exe")
	}
	hooks := CodexConfig(filepath.Join(t.TempDir(), "missing-guardrail.exe"))["hooks"].(map[string]any)
	group := hooks["PreToolUse"].([]any)[0].(map[string]any)
	command := group["hooks"].([]any)[0].(map[string]any)["commandWindows"].(string)
	cmd := exec.Command(os.Getenv("ComSpec"), "/d", "/s", "/c", command)
	cmd.Stdin = strings.NewReader(`{"session_id":"fixture","hook_event_name":"PreToolUse"}`)
	var stdout strings.Builder
	var stderr strings.Builder
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	_ = cmd.Run()
	if got := cmd.ProcessState.ExitCode(); got != 0 {
		t.Fatalf("exit = %d, want 0; stdout=%q stderr=%q", got, stdout.String(), stderr.String())
	}
	if got := stdout.String(); !strings.Contains(got, "guardrail: transport failure: configured handler executable is unavailable") || strings.Contains(got, "handler failure") || !strings.Contains(got, `"permissionDecision":"deny"`) {
		t.Fatalf("stdout = %q, want structured transport failure only; stderr=%q", got, stderr.String())
	}
}

func TestCodexPosixCommandSeparatesPolicyAndHandlerFailures(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("POSIX hook command executes through sh")
	}
	dir := t.TempDir()
	binary := filepath.Join(dir, "guardrail")
	if err := os.WriteFile(binary, []byte("#!/bin/sh\nprintf 'guardrail: policy denial: fixture\\n' >&2\nexit \"$GUARDRAIL_TEST_EXIT\"\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	hooks := CodexConfig(binary)["hooks"].(map[string]any)
	group := hooks["PreToolUse"].([]any)[0].(map[string]any)
	command := group["hooks"].([]any)[0].(map[string]any)["command"].(string)
	for _, test := range []struct {
		name    string
		exit    string
		wantErr string
	}{
		{name: "policy", exit: "2", wantErr: "guardrail: policy denial: fixture"},
		{name: "handler", exit: "7", wantErr: "guardrail: handler failure: evaluator exited with code 7"},
	} {
		t.Run(test.name, func(t *testing.T) {
			cmd := exec.Command("sh", "-c", command)
			cmd.Env = append(os.Environ(), "GUARDRAIL_TEST_EXIT="+test.exit)
			var stderr strings.Builder
			cmd.Stderr = &stderr
			_ = cmd.Run()
			if got := cmd.ProcessState.ExitCode(); got != 2 {
				t.Fatalf("exit = %d, want 2", got)
			}
			if got := stderr.String(); !strings.Contains(got, test.wantErr) || strings.Contains(got, "transport failure") {
				t.Fatalf("stderr = %q, want %q and no transport fallback", got, test.wantErr)
			}
		})
	}
}
