package genconfig

import (
	"bytes"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode/utf16"
)

const codexHookFailureSuffix = " || { printf '%s\\n' 'guardrail: evaluator unavailable or blocked; continue independent work.' >&2; exit 2; }"
const codexWindowsHookPrefix = "powershell.exe -NoLogo -NoProfile -NonInteractive -EncodedCommand "
const codexWindowsHookFailureSuffix = " || (echo guardrail: evaluator unavailable or blocked; continue independent work. 1>&2 & exit /b 2)"

func CodexConfig(binary string) Fragment {
	// Quote the executable as a shell word, including paths with spaces/apostrophes.
	command := "'" + strings.ReplaceAll(binary, "'", "'\"'\"'") + "' hook codex" + codexHookFailureSuffix
	// Codex executes commandWindows through cmd.exe. Encode the PowerShell
	// payload so binary paths containing shell metacharacters remain data, then
	// map every evaluator failure (including a missing PowerShell) to blocking
	// exit 2 instead of cmd.exe's fail-open exit 1.
	windowsScript := "& '" + strings.ReplaceAll(binary, "'", "''") + "' hook codex; exit $LASTEXITCODE"
	commandWindows := codexWindowsHookPrefix + encodePowerShellCommand(windowsScript) + codexWindowsHookFailureSuffix
	hooks := map[string]any{}
	for _, event := range []string{"PreToolUse", "PostToolUse", "SessionStart"} {
		matcher := "*"
		if event == "PostToolUse" {
			matcher = "^apply_patch$"
		}
		hooks[event] = []any{map[string]any{
			"id": "guardrail-codex-" + event, "matcher": matcher,
			"hooks": []any{map[string]any{"type": "command", "command": command, "commandWindows": commandWindows, "timeout": 10}},
		}}
	}
	return Fragment{"hooks": hooks}
}

func encodePowerShellCommand(script string) string {
	units := utf16.Encode([]rune(script))
	raw := make([]byte, len(units)*2)
	for i, unit := range units {
		binary.LittleEndian.PutUint16(raw[i*2:], unit)
	}
	return base64.StdEncoding.EncodeToString(raw)
}

// CodexRules is a coarse native floor for command escalation, not a filesystem
// sandbox or a complete substitute for the Engine. See ADR-0016.
func CodexRules() []byte {
	var b strings.Builder
	b.WriteString("# Generated by Guardrail. Native escalation floor; see ADR-0016.\n")
	patterns := [][]string{
		{"dd"}, {"mkfs"}, {"wipefs"}, {"shred"}, {"srm"}, {"sudo"}, {"su"}, {"doas"},
		{"git", "reset", "--hard"}, {"git", "reset", "--keep"},
		{"git", "push", "--force"}, {"git", "push", "-f"},
		{"git", "clean", "-fd"}, {"git", "clean", "-df"},
		{"docker", "system", "prune"}, {"docker", "volume", "prune"},
	}
	for _, flags := range [][]string{{"-rf"}, {"-fr"}, {"-r", "-f"}, {"-f", "-r"}} {
		for _, target := range []string{"/", "~", ".", ".."} {
			pattern := append([]string{"rm"}, flags...)
			patterns = append(patterns, append(pattern, target))
		}
	}
	for _, pattern := range patterns {
		raw, _ := json.Marshal(pattern)
		fmt.Fprintf(&b, "prefix_rule(pattern = %s, decision = \"forbidden\", justification = \"Guardrail destructive-command floor; use a scoped reversible alternative.\")\n", raw)
	}
	return []byte(b.String())
}

// WriteCodexRules owns exactly one file. Refuse to replace a user-created file
// of the same name. Lifecycle disable keeps this floor, like Claude permissions.
func WriteCodexRules(hooksPath string) error {
	path := filepath.Join(filepath.Dir(hooksPath), "rules", "guardrail.rules")
	if raw, err := os.ReadFile(path); err == nil {
		if !strings.HasPrefix(string(raw), "# Generated by Guardrail.") {
			return fmt.Errorf("refusing to overwrite unowned Codex rules: %s", path)
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	f, err := os.CreateTemp(filepath.Dir(path), ".guardrail-rules-*")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name())
	if _, err = f.Write(CodexRules()); err != nil {
		f.Close()
		return err
	}
	if err = f.Close(); err != nil {
		return err
	}
	return os.Rename(f.Name(), path)
}

// CodexHooksRegistered checks all required synchronous groups. Registration
// does not prove Codex's separate hook trust or feature settings.
func CodexHooksRegistered(doc map[string]any) bool {
	hooks, _ := doc["hooks"].(map[string]any)
	for _, event := range []string{"PreToolUse", "PostToolUse", "SessionStart"} {
		groups, _ := hooks[event].([]any)
		found := false
		for _, raw := range groups {
			group, _ := raw.(map[string]any)
			if group["id"] != "guardrail-codex-"+event {
				continue
			}
			matcher, _ := group["matcher"].(string)
			if event != "PostToolUse" && matcher != "*" {
				continue
			}
			if event == "PostToolUse" && matcher != "^apply_patch$" {
				continue
			}
			handlers, _ := group["hooks"].([]any)
			for _, raw := range handlers {
				h, _ := raw.(map[string]any)
				command, _ := h["command"].(string)
				commandWindows, _ := h["commandWindows"].(string)
				if h["type"] == "command" && h["async"] != true &&
					strings.HasSuffix(command, " hook codex"+codexHookFailureSuffix) &&
					strings.HasPrefix(commandWindows, codexWindowsHookPrefix) &&
					strings.HasSuffix(commandWindows, codexWindowsHookFailureSuffix) {
					found = true
				}
			}
		}
		if !found {
			return false
		}
	}
	return true
}

// CodexRulesRegistered also detects stale generated rules for reconciliation.
func CodexRulesRegistered(hooksPath string) bool {
	raw, err := os.ReadFile(filepath.Join(filepath.Dir(hooksPath), "rules", "guardrail.rules"))
	return err == nil && bytes.Equal(raw, CodexRules())
}
